# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Office for Creative Research | A multidisciplinary research group exploring new modes of engagement with data.
email: info@ocr.nyc
description: > # this means to ignore newlines until "baseurl:"
  The Office for Creative Research is a multidisciplinary research group exploring new modes of engagement with data, through unique practices that borrow from both the arts and sciences. OCR clients are research partners, helping to pose, refine and ultimately solve difficult problems with data.
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: The_O_C_R
github_username:  O-C-R

# Build settings
markdown: kramdown
highligher: pygments
